name: Dependabot auto merge PR

on:
  workflow_run:
    workflows: ["Publish Nuget packages"]
    types:
    - completed

defaults:
  run:
    shell: pwsh

jobs:
  auto-merge-pr:
    name: Auto merge dependabot PR
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Approve and merge dependabot PR
      run: |
        $prNumber = "${{github.event.workflow_run.pull_requests[0].number}}"
        $prUrl = "https://github.com/edumserrano/dot-net-sdk-extensions/pull/$prNumber"
        gh pr merge --auto --squash "$prUrl"
        gh pr review --approve "$prUrl"
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
