name: Dependabot auto merge PR

on:
  workflow_run:
    workflows: ["Publish Nuget packages"]
    types:
    - completed

defaults:
  run:
    shell: pwsh

jobs:
  auto-merge-pr:
    name: Auto merge dependabot PR
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Approve and merge dependabot PR
      run: |
        gh auth status
        $prNumber = "${{github.event.workflow_run.pull_requests[0].number}}"
        Write-Host "before gh pr review --approve $prNumber"
        gh pr review --approve $prNumber
        Write-Host "after gh pr review --approve $prNumber"
        # gh pr merge --auto --squash $prNumber
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
