name: Dependabot auto merge PR

on:
  workflow_run:
    workflows: ["Publish Nuget packages"]
    types:
    - completed

defaults:
  run:
    shell: pwsh

jobs:
  update-lock-files:
    name: Update NuGet packages.lock.json files
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event.workflow_run.conclusion != 'success'}}
    env:
      SLN_FILEPATH : ${{github.workspace}}/DotNet.Sdk.Extensions.sln
    steps:
    - name: debug
      run: |
        $githubContext = '${{toJSON(github)}}'
        Write-Host $githubContext
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{github.event.workflow_run.head_commit.id}}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ${{env.SLN_FILEPATH}} --force-evaluate
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update NuGet lockfiles
  auto-merge-pr:
    name: Auto merge dependabot PR
    needs: [update-lock-files]
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Approve and merge dependabot PR
      run: |
        gh auth login --with-token ${{env.GITHUB_TOKEN}}
        $prNumber = "${{github.event.workflow_run.pull_requests[0].number}}"
        $prUrl = "https://github.com/edumserrano/dot-net-sdk-extensions/pull/$prNumber"
        gh pr review --approve "$prUrl"
        gh pr merge --auto --squash "$prUrl" 
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
