name: .NET

on:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  workflow_dispatch:
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      shell: pwsh
      run: dotnet restore      
    - name: Build
      shell: pwsh
      run: dotnet build --no-restore
    - name: Test
      shell: pwsh
      run: dotnet test --no-build --verbosity normal
    #- name: Run PowerShell Hello World script      
    #  run: ls -R
    #  shell: pwsh
    - name: Package DotNet.Sdk.Extensions
      shell: pwsh
      run: dotnet pack ./src/DotNet.Sdk.Extensions/DotNet.Sdk.Extensions.csproj -c Release
    - name: Pack DotNet.Sdk.Extensions.Testing
      shell: pwsh
      run: dotnet pack ./src/DotNet.Sdk.Extensions.Testing/DotNet.Sdk.Extensions.Testing.csproj -c Release
    - name: Publish DotNet.Sdk.Extensions.Testing nuget
      shell: pwsh
      run: dotnet nuget push ./*.nupkg --api-key $env:NUGET_PUSH_API_KEY --source https://api.nuget.org/v3/index.json
      working-directory: ./src/DotNet.Sdk.Extensions.Testing/bin/Release/
      env:
        NUGET_PUSH_API_KEY: ${{ secrets.NUGET_PUSH_API_KEY }}
